### ISSUE TITLE
 Unhandled Runtime Error

### ISSUE THREAD

**Issue by aiml6thsem** [lguibr/Mimeflow#1]
I have Tried all the possible way to run but getting Unhandled Runtime Error
RuntimeError: Aborted(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name))
![image](https://github.com/lguibr/Mimeflow/assets/169547756/13ca2053-b42c-45ac-8666-21e4e4a7adea)
Can you please help me with this.

**Comment by lguibr** [comment]
Hello @aiml6thsem, Sure thing, let's fix it! 

I assume you are running the project using the `dev` or `next dev` command, right? If this is the case, can you try using the combination of `build` and then `start`? Also, I believe that even on `dev,` if you change the source code and save it, it will reload and work. 

It's related to a problem with MediaPipe loading twice because of React (additional references for this issue [1](https://github.com/google/mediapipe/issues/3807),[2](https://github.com/google/mediapipe/issues/2823#issuecomment-994140622)).

Additionally, setting next.config.js strict false could also help. 

Let me know if you have any additional context or workarounds you tried.

I will step in to solve it the following Monday, 13/05/24. 🙏🏽 Please consider giving a star to this GitHub repo 🌟Thanks!

**Comment by aiml6thsem** [comment]
Thankyou very much. Let me now when you solve it.

**Comment by lguibr** [comment]
This issue has been resolved at the commit [83785d68d5b4e0cb810d1616fa6b6316a0adbd69](https://github.com/lguibr/Mimeflow/commit/83785d68d5b4e0cb810d1616fa6b6316a0adbd69)

**Comment by lguibr** [comment]
@aiml6thsem The issue is fixed. Thanks for raising 🙏🏽
